#!/bin/sh
### BEGIN INIT INFO
# Provides:          ts3server
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: TeamSpeak 3 server
# Description:       Start the TeamSpeak 3 server and associated services
#  This script will start TeamSpeak 3 server, and possibly all associated services.
### END INIT INFO

DESC="voice server"
NAME=ts3server
USER="ts3"
TS3PATH=""
TS3NAME="ts3server_startscript.sh"
PARAM="inifile=ts3server.ini"

SCRIPTNAME="${0##*/}"
SCRIPTNAME="${SCRIPTNAME##[KS][0-9][0-9]}"

ENV="env -i LANG=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

case "$1" in
  start)
	echo "Starting $DESC" "$NAME"
	echo
	su - $USER -c "./${TS3PATH}${TS3NAME} start $PARAM"
	;;
  stop)
	echo "Stopping $DESC" "$NAME"
	echo
	su - $USER -c "./${TS3PATH}${TS3NAME} stop"
	;;
  status)
	su - $USER -c "./${TS3PATH}${TS3NAME} status"
	exit $?
	;;
  restart)
	echo "Restarting $DESC" "$NAME"
	echo
	su - $USER -c "./${TS3PATH}${TS3NAME} stop"
	su - $USER -c "./${TS3PATH}${TS3NAME} start $PARAM"
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac

exit 0
